# Generated by Django 4.1.2 on 2022-10-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectimagemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectmodel'),
        ),
        migrations.AlterField(
            model_name='projectimagemodel',
            name='project_images',
            field=models.ImageField(default='projects/default.png', upload_to='projects/images'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='image',
            field=models.ImageField(default='projects/default.png', upload_to='projects/'),
        ),
        migrations.CreateModel(
            name='ProjectToolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=128)),
                ('tool_icon', models.ImageField(upload_to='projects/tools')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectmodel')),
            ],
        ),
    ]
