# Generated by Django 4.1.2 on 2022-10-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmodel_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
