# Generated by Django 4.1.2 on 2022-10-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimagemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.projectmodel'),
        ),
    ]
