# Generated by Django 4.1.2 on 2022-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectimagemodel_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='name_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='name_tr',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
