# Generated by Django 4.1.2 on 2022-10-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectmodel_description_en_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectModel',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='ProjectImageModel',
            new_name='ProjectImage',
        ),
        migrations.RenameModel(
            old_name='ProjectToolsModel',
            new_name='ProjectTool',
        ),
    ]
