# Generated by Django 4.1.2 on 2022-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default=27, max_length=128),
            preserve_default=False,
        ),
    ]
