# Generated by Django 4.1.2 on 2022-10-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_category_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttool',
            name='tool_name',
            field=models.CharField(blank=True, choices=[('flutter', 'Flutter'), ('android', 'Android'), ('java', 'Java'), ('ios', 'IOS'), ('figma', 'Figma'), ('adobexd', 'Adobe Xd'), ('django', 'Django'), ('djangorestapi', 'Django Rest Api'), ('firebase', 'Firebase')], max_length=16, null=True),
        ),
    ]
