# Generated by Django 4.1.2 on 2022-10-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_slug_alter_projecttool_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug_en',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug_tr',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
