# Generated by Django 4.1.2 on 2022-10-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_slug_en_project_slug_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttool',
            name='tool_name',
            field=models.CharField(blank=True, choices=[('flutter', 'Flutter'), ('android', 'Android'), ('java', 'Java'), ('swift', 'Swift'), ('ios', 'IOS'), ('xcode', 'Xcode'), ('django', 'Django'), ('firebase', 'Firebase'), ('figma', 'Figma'), ('adobexd', 'Adobe Xd')], max_length=16, null=True),
        ),
    ]
