# Generated by Django 4.1.2 on 2022-10-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatesmodel',
            name='company_icon',
            field=models.URLField(blank=True),
        ),
    ]
