# Generated by Django 4.1.2 on 2022-10-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_rename_certificatesmodel_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(null=True, upload_to='certificate/image'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='company_icon',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/icon'),
        ),
    ]
