# Generated by Django 4.1.2 on 2022-10-12 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='user')),
                ('description', models.TextField(blank=True)),
                ('birthday', models.DateTimeField(auto_now=True)),
                ('avaliable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=64, unique=True)),
                ('account_image', models.ImageField(upload_to='account')),
                ('account_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='user.usermodel')),
            ],
        ),
    ]
