# Generated by Django 4.1.2 on 2022-10-12 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_accounts_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_image',
            field=models.FileField(upload_to='account/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'doc', 'svg'])]),
        ),
    ]
