# Generated by Django 4.1.2 on 2022-10-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usermodel_email_usermodel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(max_length=64),
        ),
    ]
