# Generated by Django 4.1.2 on 2022-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usermodel_email_alter_usermodel_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='title_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
