# Generated by Django 4.1.2 on 2022-10-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usermodel_description_de_usermodel_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='description_de',
            new_name='description_tr',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='title_de',
            new_name='title_tr',
        ),
    ]
