# Generated by Django 4.1.2 on 2022-10-13 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_description_de_usermodel_description_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
