# Generated by Django 4.1.2 on 2022-10-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_usermodel_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountModel',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='UserImagesModel',
            new_name='UserImage',
        ),
    ]
